### ISSUE TITLE
Cám ơn bạn rất nhiều

### ISSUE THREAD

**Issue by quyenquyen** [TrongTan124/ghi-chep-devstack#1]
Mình đã cài Devstack rất nhiều lần nhưng đều bị lỗi. Mình muốn gửi lời cám ơn đến bạn nhờ có video hướng dẫn của bạn mình đã cài đặt thành công. Mong rằng bạn sẽ làm nhiều video hướng dẫn nữa nhé! Chúc bạn nhiều sức khỏe, cám ơn rất nhiều.

![image](https://user-images.githubusercontent.com/47210530/56882179-14002e80-6a8d-11e9-84db-bb01c2901ce4.png)

**Comment by TrongTan124** [comment]
OK bạn.
